### PR TITLE
Play pause fix

### PR DESCRIPTION
**Pull request by Broham**
Also removes some console.logs that we appear to have been using for debugging.  Assuming these should not be in the master branch

### CODE REVIEW

**Comment by jgoley** [comment]
⏯  This looks good. I made a tiny visual update to the buttons—changing the cursor and colors on hover.

**Comment by jgoley** [comment]
Oh, wait. Looks like you branched off of #20?

**Comment by Broham** [comment]
@jgoley - yeah I did. Sorry, did that mess you up?

**Comment by jgoley** [comment]
Oh, no worries. I suppose we should merge #20 in first?

**Comment by Broham** [comment]
Yeah - went ahead and merged

**Pull request merged**
